### ISSUE TITLE
General usage 

### ISSUE THREAD

**Issue by iammatthias** [matfin/cloudinary_to_hugo#1]
Hi Matt, 

Could you provide a brief run-down on how to use this tool? I've been reading your ["Cinematt" post](https://mattfinucane.com/projects/cinematt/), and your [cloudinary_to_hugo](https://github.com/matfin/cloudinary_to_hugo) looks like exactly what I need.

**Comment by matfin** [comment]
Sure thing. Will update the README.md this evening and merge. Stand by....

**Comment by matfin** [comment]
Hey @iammatthias,

Readme has been updated and the script has been tidied up so it should work now. Will close this issue but please shout if you encounter problems.

**Comment by iammatthias** [comment]
Thank you so much, I'll let you know how if I run into anything.
